# render.com デプロイ設定
# 全角文字数カウント修正版 SEO・AIOチェックツール

services:
  - type: web
    name: mercari-seo-checker
    env: node
    plan: free  # または starter
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
    
    # 自動デプロイ設定
    autoDeploy: true
    branch: main  # または master
    
    # ヘルスチェック設定
    healthCheck:
      httpPath: /
      timeoutSeconds: 30
    
    # ドメイン設定（オプション）
    # domains:
    #   - api.checkseoaio.com
    
    # 環境変数（プライベート情報はWeb UIで設定）
    # envVars:
    #   - key: DATABASE_URL
    #     fromDatabase:
    #       name: my-database
    #       property: connectionString
